name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get install -y libgtk-3-dev intltool imagemagick
    - name: autogen
      run: ./autogen.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: notify if build failed
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: "#github"
        SLACK_USERNAME: "GitHub Actions"
        SLACK_TITLE: "Build failed."
